-- RZ Dispatch backup created 2026-09-18T11:11:46.693Z
-- Generated by scripts/backup.js

COPY public.activity (id, initials, name, action, detail, time, created_at) FROM stdin;
0b02da77-d2c8-4468-930d-215aab9e9774	ML	Marco Lee	accepted job JO-8416	Pickup at 2100 Franklin St	2 min ago	2026-09-13T07:32:36.634Z
e0184ba6-5f42-4b9d-b9d9-b71fb0d1bb14	SK	Sarah Kim	arrived at pickup	Job JO-8414 · 900 Battery St	7 min ago	2026-09-13T07:32:36.634Z
47fecee6-e357-4610-b912-aab77138ee04	DR	Daniel Ruiz	completed delivery	Job JO-8408 · 1.2 mi trip	12 min ago	2026-09-13T07:32:36.634Z
f3a004c1-506e-45a1-96a8-df9a3a80a9b4	RZ	ZANIQ RAO	assigned JO-8421	1280 Market Street to 77 Geary Street	just now	2026-09-13T08:07:32.950Z
21cc52d6-538a-4594-a25d-296fc0886f01	RZ	ZANIQ RAO	updated JO-8423	10 Test Street to 20 Test Avenue	just now	2026-09-13T09:11:49.407Z
c9edef67-8740-4e29-b00d-9b5b06c7bb7f	RZ	ZANIQ RAO	removed JO-8423	10 Test Street to 20 Test Avenue	just now	2026-09-13T09:11:49.410Z
03bf4554-3f3a-40ed-bd0b-f4e104d2eea9	RZ	ZANIQ RAO	removed JO-8422	10 Test Street to 20 Test Avenue	just now	2026-09-13T09:12:00.844Z
c64c7738-dbdc-455a-a2ee-b8762464f35f	RZ	ZANIQ RAO	optimized dispatch route	4 active loads sequenced	just now	2026-09-13T09:15:17.934Z
30f6962f-a0ad-4292-9576-a91abcd1fa3a	RZ	ZANIQ RAO	optimized dispatch route	4 active loads sequenced	just now	2026-09-13T09:22:43.380Z
8b5b8fee-5464-425e-b374-6ac8856ad58b	RZ	ZANIQ RAO	assigned JO-8422	1 Operator Test Street to 2 Operator Test Avenue	just now	2026-09-13T10:20:53.247Z
bc470052-a8b4-4490-ba86-75b02955ee72	OP	Sarah Kim	moved JO-8422 to en_route	1 Operator Test Street to 2 Operator Test Avenue	just now	2026-09-13T10:20:53.578Z
14391619-48b1-4a0d-b2c2-3499cef6ed63	OP	Sarah Kim	uploaded proof for JO-8422	pod-test.txt	just now	2026-09-13T10:20:53.657Z
7aa4051d-aa0a-4d80-af46-37f0f256cfac	RZ	ZANIQ RAO	removed JO-8422	1 Operator Test Street to 2 Operator Test Avenue	just now	2026-09-13T10:20:53.660Z
735307af-aa47-4232-96c3-c69893d1bb2b	RZ	ZANIQ RAO	assigned JO-8422	Cleanup Test Street to Cleanup Test Avenue	just now	2026-09-13T10:21:59.988Z
698901bb-1b19-4ed3-8096-3eb7ac55a75c	OP	Sarah Kim	uploaded proof for JO-8422	cleanup-proof.pdf	just now	2026-09-13T10:22:00.343Z
29b627a9-bdcb-4580-96a7-1e1cb139a16f	RZ	ZANIQ RAO	removed JO-8422	Cleanup Test Street to Cleanup Test Avenue	just now	2026-09-13T10:22:00.347Z
7a49fc6c-7b9a-4cdc-8d73-a5db70c0be94	RZ	ZANIQ RAO	optimized dispatch route	4 active loads sequenced	just now	2026-09-13T11:17:24.113Z
0d45f276-ecef-4fda-8bf7-d97ed113033a	OP	Sarah Kim	moved JO-8421 to en_route	1280 Market Street to 77 Geary Street	just now	2026-09-13T11:19:20.209Z
aec3757a-84ac-4c37-805d-71949faef80b	OP	Sarah Kim	moved JO-8421 to arrived	1280 Market Street to 77 Geary Street	just now	2026-09-13T11:19:21.653Z
9f305b96-582a-452b-8da3-a3b2fd2a6c44	OP	Sarah Kim	moved JO-8421 to picked_up	1280 Market Street to 77 Geary Street	just now	2026-09-13T11:19:23.587Z
cf1bf494-5b98-42b1-931e-8d79725d8c92	OP	Sarah Kim	moved JO-8421 to delivered	1280 Market Street to 77 Geary Street	just now	2026-09-13T11:19:24.438Z
871a115d-a5bb-44a6-960e-9806595d242c	RZ	Admin	assigned JO-8409	601 4th Street to Pier 39	just now	2026-09-14T14:58:12.372Z
c8d0c533-5ae4-46ef-81ee-70476869aaba	RZ	Admin	assigned JO-8421	1280 Market Street to 77 Geary Street	just now	2026-09-14T14:58:14.779Z
93dffbe0-fd27-4d36-bd07-a6bf832b8c79	RZ	Admin	added vehicle TEST-777	Tesla Model Y	just now	2026-09-14T16:07:40.903Z
cc1b26b3-8699-4cec-9d4a-ef8f7f4f09f9	RZ	Admin	updated TEST-777	Tesla Model Y	just now	2026-09-14T16:07:40.911Z
56d98552-f51f-4ca0-bb30-181d1b70a41e	RZ	Admin	removed vehicle VH-009	Fleet roster updated	just now	2026-09-14T16:07:40.917Z
e9809ed4-1d9e-482e-8e23-5a6183fa16e6	RZ	Admin	added vehicle SMK-1404	Smoke Van	just now	2026-09-14T16:32:11.406Z
6538b4c3-12a1-471f-9301-ca7599467378	RZ	Admin	updated SMK-1404	Smoke Van	just now	2026-09-14T16:32:11.410Z
c8843754-3dc2-425c-a9f7-c8694dc3f05c	RZ	Admin	removed vehicle VH-009	Fleet roster updated	just now	2026-09-14T16:32:11.413Z
13cf1a59-db69-488f-9260-5da122b0fde7	RZ	Admin	added vehicle SWEEP-99	Sweep Car	just now	2026-09-14T16:34:39.615Z
ecc7c5bf-22e4-4737-8870-9ec178a6c374	RZ	Admin	added vehicle SMK-0507	Smoke Van	just now	2026-09-14T16:35:30.513Z
a55afda5-5331-4fa8-a977-e4d64cfaafbe	RZ	Admin	updated SMK-0507	Smoke Van	just now	2026-09-14T16:35:30.523Z
a772a20b-69f8-486b-922e-ab5a40ac95b7	RZ	Admin	removed vehicle VH-010	Fleet roster updated	just now	2026-09-14T16:35:30.529Z
450d7076-0b46-448c-b052-b13cd27cea9b	RZ	Admin	assigned JO-8409	601 4th Street to Pier 39	just now	2026-09-14T17:15:30.781Z
852a9eeb-3d41-4778-aef9-c214161216e8	RZ	Admin	dispatched BK-B8A0E27C	123 mission street to sfo terminal3 · JO-8424	just now	2026-09-14T17:15:54.176Z
449fec58-5995-483a-b622-4bbbb01ea43c	RZ	Admin	dispatched BK-958BC02C	123 MISSION STREET to SFO TERMINAL 3 · JO-8425	just now	2026-09-14T17:15:58.545Z
764b1509-d342-47e3-bdb7-e0ff050a3080	RZ	Admin	dispatched BK-64163760	123 Mission Street to SFO TERMINAL3 · JO-8426	just now	2026-09-14T17:16:02.739Z
daea1dd6-7c87-4504-9416-fdcff10b2ef5	RZ	Admin	dispatched BK-519ADBD4	SFO Terminal 3 to Downtown Hotel · JO-8427	just now	2026-09-14T17:16:05.532Z
ff92170a-54d4-4071-aa19-a9d9b3c48f14	RZ	Admin	dispatched BK-26B955CC	SFO Terminal 3 to Downtown Hotel · JO-8428	just now	2026-09-14T17:16:07.751Z
eb0fd02a-cbca-4166-bd2e-75c4e4c271b6	RZ	Admin	assigned JO-8421	1280 Market Street to 77 Geary Street	just now	2026-09-14T17:16:21.481Z
7cd51fde-3d13-427b-a269-a3f1143fc32b	RZ	Admin	assigned JO-8415	85 2nd Street to Mission Bay	just now	2026-09-14T17:16:31.996Z
21df7489-8669-49f4-a886-db113f103bc3	RZ	Admin	assigned JO-8418	420 Hayes Street to 16th & Valencia	just now	2026-09-14T17:16:39.976Z
03a921a9-8309-4b10-b3f7-6eda398462c3	RZ	Admin	assigned JO-8428	SFO Terminal 3 to Downtown Hotel	just now	2026-09-14T17:16:47.393Z
c1b87b0a-148d-4398-b47d-65de0a70d2db	RZ	Admin	assigned JO-8427	SFO Terminal 3 to Downtown Hotel	just now	2026-09-14T17:16:55.017Z
feb6a1ef-ea87-4568-9071-4aa44ba372f3	RZ	Admin	assigned JO-8426	123 Mission Street to SFO TERMINAL3	just now	2026-09-14T17:17:01.751Z
9f76803a-41c7-4688-8b52-c3e8d0c22956	RZ	Admin	assigned JO-8429	123 main street to sfo terminal3	just now	2026-09-14T17:18:36.562Z
decb5b03-eb6c-4006-9916-3e9c320d7a9d	RZ	Admin	optimized dispatch route	11 active loads sequenced	just now	2026-09-14T17:18:42.602Z
7fd6d593-3518-4fc9-9818-1bb90eb309c6	OP	Sarah Kim	moved JO-8421 to en_route	1280 Market Street to 77 Geary Street	just now	2026-09-14T17:23:06.392Z
70df80f8-ed07-4087-a75b-5c8f7342ada8	OP	Sarah Kim	moved JO-8421 to arrived	1280 Market Street to 77 Geary Street	just now	2026-09-14T17:23:06.563Z
1a30c817-d675-4386-8084-61042f12d6d1	OP	Sarah Kim	moved JO-8421 to picked_up	1280 Market Street to 77 Geary Street	just now	2026-09-14T17:23:06.737Z
b0c523d9-4625-4145-bce6-9ad1d32ef360	OP	Sarah Kim	moved JO-8421 to delivered	1280 Market Street to 77 Geary Street	just now	2026-09-14T17:23:06.957Z
700563dc-1583-4cd9-aefb-1a1925ee2524	OP	Sarah Kim	moved JO-8415 to en_route	85 2nd Street to Mission Bay	just now	2026-09-14T17:23:15.788Z
d50536e9-708c-4e06-815a-658861dd2987	OP	Sarah Kim	moved JO-8415 to arrived	85 2nd Street to Mission Bay	just now	2026-09-14T17:23:15.923Z
9fac01f9-ef33-4149-ae7e-e742bfb1cf2a	OP	Sarah Kim	moved JO-8415 to picked_up	85 2nd Street to Mission Bay	just now	2026-09-14T17:23:16.234Z
360c28c5-8b3b-4675-adbc-8e26a6bf59c4	OP	Sarah Kim	moved JO-8415 to delivered	85 2nd Street to Mission Bay	just now	2026-09-14T17:23:16.451Z
caa5e47d-f286-464b-aeff-7a141e3649cc	OP	Sarah Kim	moved JO-8418 to en_route	420 Hayes Street to 16th & Valencia	just now	2026-09-14T17:23:23.506Z
4b51db93-4a99-41c7-a363-d76dd54bf229	OP	Sarah Kim	moved JO-8418 to arrived	420 Hayes Street to 16th & Valencia	just now	2026-09-14T17:23:23.652Z
eb0b229d-f9fa-476c-88a0-ea3a1577f1f9	OP	Sarah Kim	moved JO-8418 to picked_up	420 Hayes Street to 16th & Valencia	just now	2026-09-14T17:23:23.814Z
b75a82e5-ecc1-4998-b767-730f01f0c059	OP	Sarah Kim	moved JO-8418 to delivered	420 Hayes Street to 16th & Valencia	just now	2026-09-14T17:23:23.970Z
5c166595-65fe-416d-8a76-fe97a6dc2576	OP	Sarah Kim	moved JO-8409 to en_route	601 4th Street to Pier 39	just now	2026-09-14T17:23:30.078Z
ce982073-f78e-4de7-a2ab-8c6818bae6a7	OP	Sarah Kim	moved JO-8409 to arrived	601 4th Street to Pier 39	just now	2026-09-14T17:23:30.228Z
97fa606a-6346-4394-b79f-533fc12c5daf	OP	Sarah Kim	moved JO-8409 to picked_up	601 4th Street to Pier 39	just now	2026-09-14T17:23:30.384Z
1619b22e-bf69-42c9-a022-a792a47f9bf4	OP	Sarah Kim	moved JO-8409 to delivered	601 4th Street to Pier 39	just now	2026-09-14T17:23:30.517Z
2959705d-08e0-490f-aae8-e4f7918c1be5	OP	Sarah Kim	moved JO-8427 to en_route	SFO Terminal 3 to Downtown Hotel	just now	2026-09-14T17:23:36.591Z
47c636c1-c18e-400e-b9ad-1b5d90eb6156	OP	Sarah Kim	moved JO-8427 to arrived	SFO Terminal 3 to Downtown Hotel	just now	2026-09-14T17:23:36.742Z
51ed6682-a6c4-435f-a5c1-cfe40cd332a0	OP	Sarah Kim	moved JO-8427 to picked_up	SFO Terminal 3 to Downtown Hotel	just now	2026-09-14T17:23:36.900Z
4e032817-dda1-4bfe-b88a-add4615e0437	OP	Sarah Kim	moved JO-8427 to delivered	SFO Terminal 3 to Downtown Hotel	just now	2026-09-14T17:23:37.130Z
9bc6faa1-44fd-4dc5-88f6-0dd21347e6e4	OP	Sarah Kim	moved JO-8428 to en_route	SFO Terminal 3 to Downtown Hotel	just now	2026-09-14T17:23:43.926Z
b2164f56-b2a9-416c-a1eb-e8b73077050e	OP	Sarah Kim	moved JO-8428 to arrived	SFO Terminal 3 to Downtown Hotel	just now	2026-09-14T17:23:44.073Z
e87bed35-deaa-4ac1-a471-2d93ab70a77b	OP	Sarah Kim	moved JO-8428 to picked_up	SFO Terminal 3 to Downtown Hotel	just now	2026-09-14T17:23:44.230Z
b903667a-326c-4deb-8d19-52ffeb6dd231	OP	Sarah Kim	moved JO-8428 to delivered	SFO Terminal 3 to Downtown Hotel	just now	2026-09-14T17:23:44.454Z
1f5ec67e-e0e5-44b9-a170-7753f35ede3c	OP	Sarah Kim	moved JO-8426 to en_route	123 Mission Street to SFO TERMINAL3	just now	2026-09-14T17:23:50.765Z
1feeba14-dffb-4e4d-81bb-d484ddbc628e	OP	Sarah Kim	moved JO-8426 to arrived	123 Mission Street to SFO TERMINAL3	just now	2026-09-14T17:23:50.917Z
f620d461-0be2-4001-ba1f-0e6bcd4b1b4c	OP	Sarah Kim	moved JO-8426 to picked_up	123 Mission Street to SFO TERMINAL3	just now	2026-09-14T17:23:51.066Z
2d3501c6-f1ba-44d6-b41e-7b3426412560	OP	Sarah Kim	moved JO-8426 to delivered	123 Mission Street to SFO TERMINAL3	just now	2026-09-14T17:23:51.293Z
62b56d15-cbeb-45bc-820c-0d7b11a2c5cb	OP	Sarah Kim	moved JO-8429 to en_route	123 main street to sfo terminal3	just now	2026-09-14T17:23:57.759Z
018fe5f5-b252-481b-8d89-b4b7ee5bef23	OP	Sarah Kim	moved JO-8429 to arrived	123 main street to sfo terminal3	just now	2026-09-14T17:23:57.915Z
84f130fa-edad-485e-824e-03f38c7ae271	OP	Sarah Kim	moved JO-8429 to picked_up	123 main street to sfo terminal3	just now	2026-09-14T17:23:58.063Z
6c18f15b-9fbe-4293-aea2-e2147e610911	OP	Sarah Kim	moved JO-8429 to delivered	123 main street to sfo terminal3	just now	2026-09-14T17:23:58.201Z
42bb01a5-5c09-4d7a-89ae-7d78a3f4e2ae	RZ	Admin	dispatched BK-D689E139	123 Market Street to SFO Terminal 3 · JO-8430	just now	2026-09-14T17:34:49.109Z
ad4ece29-0175-4173-8260-d3436bcaf6e2	RZ	Admin	dispatched BK-6AC178B3	123 Market Street to SFO Terminal 3 · JO-8431	just now	2026-09-14T17:36:54.422Z
eb307feb-d6c7-4330-9ca4-ffe00082f091	RZ	Admin	dispatched BK-3AA3F751	123 Market Street to SFO Terminal 3 · JO-8432	just now	2026-09-14T17:38:21.437Z
097f24db-1f5b-4824-bff8-7915dab98f7a	RZ	Admin	assigned JO-XT1	A St to B St	just now	2026-09-14T17:40:58.921Z
757d24eb-c739-4304-9255-dde479d3337e	RZ	Admin	assigned JO-XT2	C St to D St	just now	2026-09-14T17:40:59.150Z
1e3f7ba6-1288-4395-85b4-fa1b18d7fd65	RZ	Admin	updated VAN-0842	Ford Transit	just now	2026-09-14T17:43:50.966Z
767302a2-82ed-46ae-a3dc-8e58da5f59fb	RZ	Admin	updated TRK-2100	Ford F-550	just now	2026-09-14T17:43:56.507Z
e582ff13-e28d-4f5d-b7a4-53c88eaf08a6	RZ	Admin	updated VAN-3391	Ram ProMaster	just now	2026-09-14T17:43:59.580Z
7d47e28c-e827-44c0-ab6a-0a7a7029a594	RZ	Admin	updated SUV-5530	Toyota Highlander	just now	2026-09-14T17:44:02.106Z
748006d7-8549-4c2e-ac31-f6c57f94ba91	RZ	Admin	updated VAN-1280	Ford Transit	just now	2026-09-14T17:46:23.360Z
1b20216e-c3c0-4621-b501-b0c7ae2d83f5	RZ	Admin	dispatched BK-D1C74C70	SFO Terminal 3 to Downtown Hotel · JO-8430	just now	2026-09-14T17:52:40.760Z
68031d7a-3880-4897-a1c5-2c203952ec26	RZ	Admin	dispatched BK-525BAA69	123 Market Street to SFO Terminal 3 · JO-8431	just now	2026-09-14T18:06:55.808Z
b94b44fe-0120-4604-8026-3c28a037f569	RZ	Admin	dispatched BK-C9BA708C	SFO Terminal 3 to Downtown Hotel · JO-8431	just now	2026-09-14T18:08:06.148Z
b2c5704a-b80b-46e5-9783-aa9ab4e11076	RZ	Admin	dispatched BK-FB8097C4	123 Market Street to SFO Terminal 3 · JO-8432	just now	2026-09-14T18:08:25.454Z
7b7a5c68-10fa-4668-ad28-b55e19052f09	RZ	Admin	dispatched BK-A1447B73	12 Front St to SFO Terminal 2 · JO-8432	just now	2026-09-15T11:27:39.165Z
0eb86ab5-fa09-4952-b889-41ce83630908	RZ	Admin	dispatched BK-CBF4647C	12 Front St to SFO Terminal 2 · JO-8433	just now	2026-09-15T11:27:39.366Z
f61780c9-74df-4ff3-abc2-114e4facece5	RZ	Admin	dispatched BK-41E9ACA9	12 Front St to SFO Terminal 2 · JO-8432	just now	2026-09-15T11:29:20.060Z
bcbec372-bc7f-4aaf-aeac-d89125edea39	RZ	Admin	dispatched BK-A477B3BA	12 Front St to SFO Terminal 2 · JO-8433	just now	2026-09-15T11:29:20.160Z
a87ad198-8680-42da-a653-8df831792ab6	RZ	Admin	dispatched BK-F583955D	123 Market Street to SFO Terminal 3 · JO-8432	just now	2026-09-15T11:31:55.727Z
422d6a0d-bdb7-45b5-b16f-16bc355a8951	RZ	Admin	updated JO-8432	Updated From to FT To	just now	2026-09-15T14:08:10.964Z
85c49ef5-a961-4af5-ba87-f88df499e86a	RZ	Admin	removed JO-8432	Updated From to FT To	just now	2026-09-15T14:08:10.989Z
646a17b0-0e98-4e83-b388-9d3aee383c19	RZ	Admin	dispatched BK-FF28515C	FT Pickup to FT Dropoff · JO-8432	just now	2026-09-15T14:08:11.130Z
4f58092b-063b-49e5-a359-1ed028678e72	RZ	Admin	added vehicle FT-1234	Ford Test Van	just now	2026-09-15T14:08:11.185Z
4072f33c-d305-48f7-b76e-a8788cd5702f	RZ	Admin	updated FT-5678	Ford Updated Model	just now	2026-09-15T14:08:11.210Z
982c6108-a18a-4204-9a50-08b91c515f8d	RZ	Admin	removed vehicle VH-009	Fleet roster updated	just now	2026-09-15T14:08:11.222Z
a2a71189-3c82-4e98-8cd0-e099a569a929	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T14:08:11.255Z
21718c96-6168-48b7-8fdd-20ed98e208a3	RZ	Admin	dispatched BK-946BB47F	A to B · JO-8432	just now	2026-09-15T14:08:11.358Z
3eb43eea-4ffd-4e54-98b4-b7bb76bba47e	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-15T14:08:11.422Z
4123598d-85d0-439d-8130-296a76e0fdac	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T14:08:11.445Z
cbf8c7ae-5f32-444e-87e4-594b3d8741a7	OP	Sarah Kim	moved JO-8432 to en_route	Op Test to Op Dest	just now	2026-09-15T14:08:11.466Z
f90fdc65-3411-4179-8414-2557981c345d	OP	Sarah Kim	moved JO-8432 to arrived	Op Test to Op Dest	just now	2026-09-15T14:08:11.477Z
c8c89f74-8662-4e30-9827-1d1a26efd879	OP	Sarah Kim	moved JO-8432 to picked_up	Op Test to Op Dest	just now	2026-09-15T14:08:11.487Z
cdb596db-8f85-4d0c-a731-29db1f379a2f	OP	Sarah Kim	moved JO-8432 to delivered	Op Test to Op Dest	just now	2026-09-15T14:08:11.497Z
29724616-51c4-42e6-af09-c9a44957065b	OP	Sarah Kim	uploaded proof for JO-8432	test.png	just now	2026-09-15T14:08:11.514Z
45c5bb3b-ecd4-4028-a415-161bceadbe26	RZ	Admin	updated JO-8432	Updated From to FT To	just now	2026-09-15T14:12:11.970Z
b8b5e312-fd4b-475e-bfc3-e4e7f45347f8	RZ	Admin	removed JO-8432	Updated From to FT To	just now	2026-09-15T14:12:11.999Z
08dab659-7f81-46c1-9e36-631b18a3138b	RZ	Admin	dispatched BK-AB12F16C	FT Pickup to FT Dropoff · JO-8432	just now	2026-09-15T14:12:12.137Z
e0694db5-7e4c-49db-9397-5b80e0abc558	RZ	Admin	added vehicle FT-1234	Ford Test Van	just now	2026-09-15T14:12:12.197Z
800d42bc-23a7-4600-9edb-a5353eb3a648	RZ	Admin	updated FT-5678	Ford Updated Model	just now	2026-09-15T14:12:12.218Z
7917bf85-36d2-467c-8ff9-44ef1589fd91	RZ	Admin	removed vehicle VH-009	Fleet roster updated	just now	2026-09-15T14:12:12.229Z
7228bf23-edb0-44a7-88d4-5ffce623f428	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T14:12:12.264Z
9ab593ee-5ca2-4e46-9256-b4531117e9b8	RZ	Admin	assigned JO-8433	Marco Lee · VAN-1280	just now	2026-09-15T14:12:12.328Z
d8d9bc65-8266-4b26-a242-f42fd160b507	RZ	Admin	dispatched BK-E3544D0B	A to B · JO-8432	just now	2026-09-15T14:12:12.391Z
92d14c53-7783-44a3-bcc9-6467b571e1f7	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-15T14:12:12.448Z
2910c0f1-409a-4c4a-a261-aae9347fd16b	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T14:12:12.472Z
18c770b1-7983-4a9d-8daa-493b602aa239	OP	Sarah Kim	moved JO-8432 to en_route	Op Test to Op Dest	just now	2026-09-15T14:12:12.492Z
3f8b2a89-c049-4807-b852-b1bae0ae0c69	OP	Sarah Kim	moved JO-8432 to arrived	Op Test to Op Dest	just now	2026-09-15T14:12:12.503Z
9c69e2b9-df31-4aa5-9246-5b40e018b269	OP	Sarah Kim	moved JO-8432 to picked_up	Op Test to Op Dest	just now	2026-09-15T14:12:12.514Z
b1c3ac63-e360-4508-8a2d-46bae26b782e	OP	Sarah Kim	moved JO-8432 to delivered	Op Test to Op Dest	just now	2026-09-15T14:12:12.524Z
60648505-6cc0-4fc2-9eda-742e85c0acdb	OP	Sarah Kim	uploaded proof for JO-8432	test.png	just now	2026-09-15T14:12:12.542Z
13ca35b3-b9bd-4bb7-a428-feba156a0f20	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T14:13:59.782Z
9f9a7838-cc34-4a94-b2ca-d4e722024972	OP	Sarah Kim	uploaded proof for JO-8432	t.png	just now	2026-09-15T14:13:59.798Z
6bb30800-7a20-4336-acc0-06c59bda6274	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T14:15:06.526Z
656d705d-0286-454b-99eb-6669b27e41e7	OP	Sarah Kim	uploaded proof for JO-8432	t.png	just now	2026-09-15T14:15:06.542Z
7495042f-f1fd-45ce-b451-3dfa47587286	RZ	Admin	updated JO-8432	Updated From to FT To	just now	2026-09-15T14:21:59.424Z
4010105a-d10b-47c1-9ab4-1b76d1a92eea	RZ	Admin	removed JO-8432	Updated From to FT To	just now	2026-09-15T14:21:59.459Z
fb2191a4-b3d7-4547-a9a6-f4ff85a492fd	RZ	Admin	dispatched BK-592DC2B3	FT Pickup to FT Dropoff · JO-8432	just now	2026-09-15T14:21:59.676Z
be0f4d08-d164-4fa7-829f-87f8e7234f97	RZ	Admin	added vehicle FT-1234	Ford Test Van	just now	2026-09-15T14:21:59.737Z
699304f1-6ae9-4dd1-bd3b-4e8a848ecc98	RZ	Admin	updated FT-5678	Ford Updated Model	just now	2026-09-15T14:21:59.759Z
32c4ea2e-5dfb-4549-9d35-5815ece1fa1e	RZ	Admin	removed vehicle VH-009	Fleet roster updated	just now	2026-09-15T14:21:59.775Z
d01ce785-ab96-4a14-8bae-6211b6f33d78	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T14:21:59.814Z
44b65579-7383-4486-aaa5-561ddd40bf08	RZ	Admin	assigned JO-8433	Marco Lee · VAN-1280	just now	2026-09-15T14:21:59.884Z
f84676a0-d603-45f3-9b66-1179edb2eec9	RZ	Admin	dispatched BK-6A3DB6AE	A to B · JO-8432	just now	2026-09-15T14:21:59.966Z
9cd73be6-6de3-4c58-967c-64dff4d0e9dc	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-15T14:22:00.050Z
3187ce51-8fd8-4871-a84c-4f57fe51dc65	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T14:22:00.079Z
a3e5e0e0-a027-4521-ac62-08b7cfc5263a	OP	Sarah Kim	moved JO-8432 to en_route	Op Test to Op Dest	just now	2026-09-15T14:22:00.109Z
ad97ac5b-ed55-48f1-aa45-6f3ef4aa773a	OP	Sarah Kim	moved JO-8432 to arrived	Op Test to Op Dest	just now	2026-09-15T14:22:00.123Z
a96d6377-0eb2-4f58-b1e5-8c8c1a3dabe4	OP	Sarah Kim	moved JO-8432 to picked_up	Op Test to Op Dest	just now	2026-09-15T14:22:00.136Z
b7787763-be7f-4fbe-ac0f-a7ea52f12b31	OP	Sarah Kim	moved JO-8432 to delivered	Op Test to Op Dest	just now	2026-09-15T14:22:00.150Z
02f99372-1f6a-4f0e-8047-4cb0c4b59163	OP	Sarah Kim	uploaded proof for JO-8432	test.png	just now	2026-09-15T14:22:00.171Z
6da66afa-0eeb-4864-9904-ba32354b09ad	RZ	Admin	updated JO-8432	Updated From to FT To	just now	2026-09-15T14:22:19.240Z
26191de2-9573-41e6-b9fb-8f1d79f65d9f	RZ	Admin	removed JO-8432	Updated From to FT To	just now	2026-09-15T14:22:19.260Z
c80920ba-90a7-4923-b32a-9ef93a6b57a2	RZ	Admin	dispatched BK-E285E998	FT Pickup to FT Dropoff · JO-8432	just now	2026-09-15T14:22:19.375Z
5b98099e-70e0-4034-bc62-f6c192c27048	RZ	Admin	added vehicle FT-1234	Ford Test Van	just now	2026-09-15T14:22:19.440Z
1cc377d1-1f90-4cdc-88e8-ecec0559b433	RZ	Admin	updated FT-5678	Ford Updated Model	just now	2026-09-15T14:22:19.461Z
c92579a9-6688-49de-b5f9-a50531686b47	RZ	Admin	removed vehicle VH-009	Fleet roster updated	just now	2026-09-15T14:22:19.470Z
7a096c84-dc14-4b90-9158-d41c97285e85	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T14:22:19.498Z
274ca837-44f3-4842-acbf-cf3efdae3e54	RZ	Admin	assigned JO-8433	Marco Lee · VAN-1280	just now	2026-09-15T14:22:19.541Z
d5ad5677-902d-4676-b9e9-d9adadd9372e	RZ	Admin	dispatched BK-F7E1FB65	A to B · JO-8432	just now	2026-09-15T14:22:19.592Z
eb34f804-eac3-4509-a633-945bda4420bf	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-15T14:22:19.625Z
5889a6e6-9c2d-445f-ba4a-7c9e2a2d44ec	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T14:22:19.641Z
3cc28bc7-6658-4f90-9114-c1fbf7e64251	OP	Sarah Kim	moved JO-8432 to en_route	Op Test to Op Dest	just now	2026-09-15T14:22:19.655Z
813feb86-38ee-49d8-a62e-c67e5e896c44	OP	Sarah Kim	moved JO-8432 to arrived	Op Test to Op Dest	just now	2026-09-15T14:22:19.662Z
aaed1472-870b-4928-8857-ab38511136ef	OP	Sarah Kim	moved JO-8432 to picked_up	Op Test to Op Dest	just now	2026-09-15T14:22:19.668Z
d05ba006-72b4-4014-8a11-dd86ceebf61f	OP	Sarah Kim	moved JO-8432 to delivered	Op Test to Op Dest	just now	2026-09-15T14:22:19.675Z
64450a0d-e293-45a2-ae48-b460e3c5048f	OP	Sarah Kim	uploaded proof for JO-8432	test.png	just now	2026-09-15T14:22:19.685Z
17b9c05b-e26e-4e2f-b5d5-100160755f5c	RZ	Admin	added driver Feature Test Driver	Van 42 · Available	just now	2026-09-15T17:22:01.079Z
407fb386-b92f-461f-9c5f-11f3ebe5dc2e	RZ	Admin	updated driver Feature Test Driver Renamed	Status: Offline	just now	2026-09-15T17:22:01.140Z
7c0058b2-6f53-4fc6-a442-ade5fb3eb386	RZ	Admin	updated driver Feature Test Driver Renamed	Status: Available	just now	2026-09-15T17:22:01.156Z
ac011bff-395d-475d-afc0-0ba4aeb19a07	RZ	Admin	assigned JO-8432	Feature Test Driver Renamed · SED-9201	just now	2026-09-15T17:22:01.164Z
4113c3f9-31f8-4e56-abb8-8cd1058273d7	RZ	Admin	removed driver DR-005	Roster updated	just now	2026-09-15T17:22:01.352Z
71c3d911-dd67-483f-8321-96284245001e	RZ	Admin	added driver UI Test Driver	Van 77 · Available	just now	2026-09-15T17:23:27.837Z
72351a35-3dc8-4324-98c0-ecb47d28b544	RZ	Admin	updated driver UI Test Driver	Status: Available	just now	2026-09-15T17:23:27.901Z
dedcc2b0-e1ad-4ba2-abfd-1f21b0b6ebae	RZ	Admin	updated driver UI Test Driver	Status: Offline	just now	2026-09-15T17:23:27.928Z
6478a175-508a-4728-ac53-dc41a96fbd0f	RZ	Admin	added driver UI Test Driver 263711	Van 77 · Available	just now	2026-09-15T17:27:43.839Z
b14cca1a-b22a-45ab-a354-6cd240c3ebd2	RZ	Admin	added driver UI Test Driver 494054	Van 77 · Available	just now	2026-09-15T17:31:34.550Z
0afed969-06e3-421c-a713-754f5235b8c1	RZ	Admin	updated driver UI Test Driver 494054	Status: Available	just now	2026-09-15T17:31:42.593Z
0ec737b0-7406-4e64-bbef-21bb0192f2b5	RZ	Admin	updated driver UI Test Driver 494054	Status: Offline	just now	2026-09-15T17:31:42.620Z
0353c503-6939-4adc-8dc7-255cd524b6f8	RZ	Admin	removed driver DR-005	Roster updated	just now	2026-09-15T17:31:44.451Z
cbe627f0-ba4f-43d7-a052-a6aef1d03d95	RZ	Admin	added driver UI Test Driver 568166	Van 77 · Available	just now	2026-09-15T17:32:48.319Z
74befa89-73fd-40e3-b9ec-01292d0c6858	RZ	Admin	updated driver UI Test Driver 568166	Status: Available	just now	2026-09-15T17:32:48.383Z
c359afcf-5c7f-43d7-8338-3ebd97fc2263	RZ	Admin	updated driver UI Test Driver 568166	Status: Offline	just now	2026-09-15T17:32:48.419Z
fd8efd36-0d43-43d6-9f1a-929a37cb0fae	RZ	Admin	removed driver DR-005	Roster updated	just now	2026-09-15T17:32:50.271Z
3a5f466c-32ae-43d5-9fa1-961012ba9608	RZ	Admin	updated JO-8432	Updated From to FT To	just now	2026-09-15T17:32:58.109Z
5a0eacb2-73ae-4bc1-8f20-202481449346	RZ	Admin	removed JO-8432	Updated From to FT To	just now	2026-09-15T17:32:58.122Z
49c39d10-2369-46b6-9032-0508f355deff	RZ	Admin	dispatched BK-05B811EE	FT Pickup to FT Dropoff · JO-8432	just now	2026-09-15T17:32:58.211Z
1228e796-8a57-47bf-8fe4-c4797f206b97	RZ	Admin	added vehicle FT-1234	Ford Test Van	just now	2026-09-15T17:32:58.242Z
7339d048-580e-4325-9f88-febd79bbd399	RZ	Admin	updated FT-5678	Ford Updated Model	just now	2026-09-15T17:32:58.252Z
39103e7d-e1d3-4fa8-bc8c-17c01cbedcdc	RZ	Admin	removed vehicle VH-009	Fleet roster updated	just now	2026-09-15T17:32:58.257Z
3bd08112-a789-41ad-8d0e-d0645f8517f6	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T17:32:58.272Z
705d0baf-bcde-4f2d-b69c-fbea57d9c9c8	RZ	Admin	assigned JO-8433	Marco Lee · VAN-1280	just now	2026-09-15T17:32:58.296Z
6b77b29a-4a1a-4b65-9d37-bec6cc5c926f	RZ	Admin	dispatched BK-BB86E5D0	A to B · JO-8432	just now	2026-09-15T17:32:58.331Z
cce15978-c696-458a-882f-8b4151789588	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-15T17:32:58.360Z
4a291092-af15-43ae-a9d5-e6573fb30f82	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T17:32:58.371Z
4947432d-3e08-4517-b11c-216a7507e164	OP	Sarah Kim	moved JO-8432 to en_route	Op Test to Op Dest	just now	2026-09-15T17:32:58.383Z
5d0da740-6b35-4168-ae7f-0bb5a3193492	OP	Sarah Kim	moved JO-8432 to arrived	Op Test to Op Dest	just now	2026-09-15T17:32:58.390Z
5294bef2-dff6-4bef-8267-a599952c47b9	OP	Sarah Kim	moved JO-8432 to picked_up	Op Test to Op Dest	just now	2026-09-15T17:32:58.397Z
2699bb39-500c-49f2-9221-440c2971bf43	OP	Sarah Kim	moved JO-8432 to delivered	Op Test to Op Dest	just now	2026-09-15T17:32:58.403Z
43c10d10-a9e2-4fb8-8249-f0db272f4bb0	OP	Sarah Kim	uploaded proof for JO-8432	test.png	just now	2026-09-15T17:32:58.412Z
fb32c9fa-e016-4e9d-9d7d-f5cc1b7b8d02	RZ	Admin	updated driver Avery Chen	Status: Available	just now	2026-09-15T17:33:24.794Z
3a848fb4-af56-4b63-849b-2d8409603d34	RZ	Admin	updated driver Marco Lee	Status: Offline	just now	2026-09-15T17:33:30.027Z
9416d514-1cc7-43a7-9593-451da200493f	RZ	Admin	updated driver Marco Lee	Status: Available	just now	2026-09-15T17:33:33.360Z
b7413a5f-04ba-427f-b709-812f330aeaba	RZ	Admin	updated driver Sarah Kim	Status: On route	just now	2026-09-15T17:33:36.124Z
46e6df98-fd14-4658-b7df-a37a77130b99	RZ	Admin	updated driver Avery Chen	Status: On route	just now	2026-09-15T17:33:38.911Z
3ad6a93a-aa97-422e-bb3e-a68076c33312	RZ	Admin	updated driver Sarah Kim	Status: On route	just now	2026-09-15T17:33:46.773Z
66c76284-64d8-433e-8c06-f5d7ddace4c3	RZ	Admin	updated driver Marco Lee	Status: On route	just now	2026-09-15T17:34:10.422Z
8b0d08f0-b8a0-472d-a65a-2bbc8f1d0702	RZ	Admin	added driver zaniq	No vehicle · Available	just now	2026-09-15T17:34:33.415Z
2808cebc-70b5-4c3d-94bc-97dffcdfa6ef	RZ	Admin	removed driver DR-005	Roster updated	just now	2026-09-15T17:34:42.469Z
d5a5efba-92d2-4627-bf32-c685e8a62676	RZ	Admin	added vehicle VAN-98	mercedez transit	just now	2026-09-15T17:35:28.643Z
066188a6-ac4d-4fba-8033-6c8c6c8a405a	RZ	Admin	updated VAN-1280	Ford Transit	just now	2026-09-15T17:35:48.289Z
46852bee-057e-42c7-aeac-75d05907d02d	RZ	Admin	updated VAN-1280	Ford Transit	just now	2026-09-15T17:35:50.498Z
397603d8-0fb2-4a5c-8051-40d8654ebcc1	RZ	Admin	updated VAN-1280	Ford Transit	just now	2026-09-15T17:35:53.089Z
123720e8-a0eb-4aad-8270-a848d4c31a0f	RZ	Admin	updated VAN-1280	Ford Transit	just now	2026-09-15T17:35:56.466Z
1b04e29c-a0ac-4488-a7bb-7b8fae787cee	RZ	Admin	updated VAN-1280	Ford Transit	just now	2026-09-15T17:35:58.898Z
8647a6ba-757f-48a3-a4a2-a656c7d512b7	RZ	Admin	updated driver Sarah Kim	Status: On route	just now	2026-09-15T17:36:23.867Z
c3719c87-0fdc-40fb-97ef-37abff487a1b	RZ	Admin	updated JO-8430	SFO Terminal 3 to Downtown Hotel	just now	2026-09-15T17:36:47.522Z
d62acb4a-5b87-49fe-944d-c541bdc6748d	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T17:37:34.984Z
e116abe6-ed08-410f-ab76-40060f10b5c9	RZ	Admin	removed JO-8432	OnRoute Test Origin to OnRoute Test Dest	just now	2026-09-15T17:37:36.172Z
93238ea5-abb1-4591-b09c-40e5bd0272c3	RZ	Admin	updated driver Marco Lee	Status: On route	just now	2026-09-15T17:38:16.766Z
b3da9c3d-c2ee-407f-a087-5e33aefcf9b0	RZ	Admin	updated driver Marco Lee	Status: Offline	just now	2026-09-15T17:38:27.298Z
f58d993f-f886-4e1a-8ceb-454975fd4329	RZ	Admin	updated driver Marco Lee	Status: Available	just now	2026-09-15T17:38:29.300Z
4d95fd63-d3e4-48c2-a85e-baed04c246fd	RZ	Admin	updated JO-8432	Updated From to FT To	just now	2026-09-15T17:50:21.493Z
65073f30-cd9e-4308-93bb-ee50a705aab4	RZ	Admin	removed JO-8432	Updated From to FT To	just now	2026-09-15T17:50:21.508Z
161a5c55-f4c8-404e-a010-3aba5392d290	RZ	Admin	dispatched BK-023F32E0	FT Pickup to FT Dropoff · JO-8432	just now	2026-09-15T17:50:21.601Z
40f563f7-49a8-4fbc-b5ea-24e3459c46a6	RZ	Admin	added vehicle FT-1234	Ford Test Van	just now	2026-09-15T17:50:21.628Z
275bc769-593f-4858-82d2-0b1861a17b5a	RZ	Admin	updated FT-5678	Ford Updated Model	just now	2026-09-15T17:50:21.637Z
cfab7b87-69d9-4181-a428-c53ec519d47c	RZ	Admin	removed vehicle VH-010	Fleet roster updated	just now	2026-09-15T17:50:21.643Z
8e4d1194-23d9-4a3f-af31-7f416b6fbf31	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T17:50:21.657Z
06fc9cbf-e3f5-45f4-b262-b136ea9c2d98	RZ	Admin	assigned JO-8433	Marco Lee · VAN-1280	just now	2026-09-15T17:50:21.681Z
6cd29ecd-0a91-495f-b231-139ed6d23c6f	RZ	Admin	dispatched BK-D7F92245	A to B · JO-8432	just now	2026-09-15T17:50:21.716Z
392d65f9-d309-4d99-a10b-6b3dedc518d2	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-15T17:50:21.744Z
8d551632-f188-4fa2-9596-7554b5fdc54d	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T17:50:21.756Z
6d507af4-6cd0-464f-9fb4-e08edfbc5f8e	OP	Sarah Kim	moved JO-8432 to en_route	Op Test to Op Dest	just now	2026-09-15T17:50:21.769Z
28ae273a-6224-4717-b019-a66854dcd91b	OP	Sarah Kim	moved JO-8432 to arrived	Op Test to Op Dest	just now	2026-09-15T17:50:21.776Z
a3036ca8-3ff6-43e6-bda0-68ce433b5480	OP	Sarah Kim	moved JO-8432 to picked_up	Op Test to Op Dest	just now	2026-09-15T17:50:21.782Z
aaf2e019-2fa4-4622-9107-c4c1fbb8f638	OP	Sarah Kim	moved JO-8432 to delivered	Op Test to Op Dest	just now	2026-09-15T17:50:21.788Z
7c5ac6a0-f4b2-4e26-9f58-a75b9cb72bff	OP	Sarah Kim	uploaded proof for JO-8432	test.png	just now	2026-09-15T17:50:21.798Z
14b2be1b-d77d-42a5-b42d-cc366ead3259	RZ	Admin	updated JO-8432	Updated From to FT To	just now	2026-09-15T18:12:43.353Z
b44788ec-0596-4c05-8300-b91a820c2d25	RZ	Admin	removed JO-8432	Updated From to FT To	just now	2026-09-15T18:12:43.366Z
d0a80377-7028-43d6-a482-bb86309ccc49	RZ	Admin	dispatched BK-EA946BEC	FT Pickup to FT Dropoff · JO-8432	just now	2026-09-15T18:12:43.452Z
45ab7a8e-17c0-4666-961a-2c8019f26a17	RZ	Admin	added vehicle FT-1234	Ford Test Van	just now	2026-09-15T18:12:43.479Z
280fb0eb-95c7-4754-bb10-e38e43b119e9	RZ	Admin	updated FT-5678	Ford Updated Model	just now	2026-09-15T18:12:43.488Z
d8373ca7-2e81-49ab-9d01-0bc1f8b84346	RZ	Admin	removed vehicle VH-010	Fleet roster updated	just now	2026-09-15T18:12:43.493Z
c5a67ef0-e7f7-4cb3-b26a-59577906ea93	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T18:12:43.507Z
ba4add0a-0978-4b46-ba2d-3047346146b6	RZ	Admin	assigned JO-8433	Marco Lee · VAN-1280	just now	2026-09-15T18:12:43.530Z
f17832f7-f29d-4430-b77d-41a4673f3f55	RZ	Admin	dispatched BK-93E9BBD8	A to B · JO-8432	just now	2026-09-15T18:12:43.560Z
3b570ed6-6c04-4130-9d28-bf62949b9d43	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-15T18:12:43.585Z
9be067ce-7701-4bc0-beec-7836f11ced0a	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-15T18:12:43.595Z
424352de-ee84-40e8-b863-e719d27853c8	OP	Sarah Kim	moved JO-8432 to en_route	Op Test to Op Dest	just now	2026-09-15T18:12:43.607Z
ca9b1a0d-155a-4076-af81-4ef46f1e9f2d	OP	Sarah Kim	moved JO-8432 to arrived	Op Test to Op Dest	just now	2026-09-15T18:12:43.613Z
5da3412a-0e10-4b2a-aa29-5154e4bcac27	OP	Sarah Kim	moved JO-8432 to picked_up	Op Test to Op Dest	just now	2026-09-15T18:12:43.618Z
cdaf63f6-0fb2-4eb0-bc19-b0a56113b0c1	OP	Sarah Kim	moved JO-8432 to delivered	Op Test to Op Dest	just now	2026-09-15T18:12:43.624Z
0a490243-836f-4e1d-8b38-07e3c5c3157b	OP	Sarah Kim	uploaded proof for JO-8432	test.png	just now	2026-09-15T18:12:43.632Z
2b76ae4a-099f-4e1f-956f-f67129dbb61a	RZ	Admin	updated JO-8432	Updated From to FT To	just now	2026-09-17T11:35:46.432Z
742da5f6-c197-4285-a209-e22418bd1cff	RZ	Admin	removed JO-8432	Updated From to FT To	just now	2026-09-17T11:35:46.447Z
f57bfd34-fa9f-4a82-ab13-b808e302a612	RZ	Admin	dispatched BK-2FB18CD3	FT Pickup to FT Dropoff · JO-8432	just now	2026-09-17T11:35:46.541Z
b6e2e5ab-23c4-4a67-9a97-ae24af19e6df	RZ	Admin	added vehicle FT-1234	Ford Test Van	just now	2026-09-17T11:35:46.564Z
d69f116b-930f-406f-9329-a831ef53315b	RZ	Admin	updated FT-5678	Ford Updated Model	just now	2026-09-17T11:35:46.571Z
9766084e-ca81-4ead-865a-1963f9ef943e	RZ	Admin	removed vehicle VH-010	Fleet roster updated	just now	2026-09-17T11:35:46.575Z
2e18a931-0cfd-44e7-9239-458d42e812ff	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-17T11:35:46.585Z
612fca99-2c61-4eac-ae56-ef14929703a2	RZ	Admin	assigned JO-8433	Marco Lee · VAN-1280	just now	2026-09-17T11:35:46.601Z
687139e9-cff2-4cf9-bb35-975afc2c4d38	RZ	Admin	dispatched BK-2266B03C	A to B · JO-8432	just now	2026-09-17T11:35:46.624Z
48cb2bba-ee2f-400a-bcd4-26fb7dd95a23	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-17T11:35:46.644Z
9aa246db-c1d7-44cf-92aa-e6b2f01bf978	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-17T11:35:46.651Z
766e9b8a-0947-4cb1-b649-b9fed860c251	OP	Sarah Kim	moved JO-8432 to en_route	Op Test to Op Dest	just now	2026-09-17T11:35:46.658Z
0835f478-9d49-40e3-97fb-2a9a657c0d43	OP	Sarah Kim	moved JO-8432 to arrived	Op Test to Op Dest	just now	2026-09-17T11:35:46.666Z
89331df3-a868-4fde-869a-2b902a83f04b	OP	Sarah Kim	moved JO-8432 to picked_up	Op Test to Op Dest	just now	2026-09-17T11:35:46.672Z
e2e08f06-3183-4ac3-8f23-4530778b8816	OP	Sarah Kim	moved JO-8432 to delivered	Op Test to Op Dest	just now	2026-09-17T11:35:46.676Z
8b694932-7b82-42f5-a638-c247e8e8531f	OP	Sarah Kim	uploaded proof for JO-8432	test.png	just now	2026-09-17T11:35:46.682Z
21bda6f4-9ecd-4cc9-b2ed-19a35d38e3db	RZ	Admin	updated JO-8432	Updated From to FT To	just now	2026-09-17T11:41:10.244Z
d271620d-a8d0-49c0-85c1-073581088933	RZ	Admin	removed JO-8432	Updated From to FT To	just now	2026-09-17T11:41:10.259Z
9a0070ed-1e79-49be-826f-e8ae8e6d6923	RZ	Admin	dispatched BK-DAAFFCDA	FT Pickup to FT Dropoff · JO-8432	just now	2026-09-17T11:41:10.353Z
a4a38992-c478-49b7-92fe-36cea5cd4a03	RZ	Admin	added vehicle FT-1234	Ford Test Van	just now	2026-09-17T11:41:10.385Z
f4667b65-a06c-4160-8463-297a1ad98e45	RZ	Admin	updated FT-5678	Ford Updated Model	just now	2026-09-17T11:41:10.398Z
1377477b-d630-4fca-91ba-517ff05b3afc	RZ	Admin	removed vehicle VH-010	Fleet roster updated	just now	2026-09-17T11:41:10.407Z
86c5e05f-b405-4a74-a1e3-3014583b915a	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-17T11:41:10.425Z
253c7dc3-66c5-4f99-b7ee-7d2b3941d318	RZ	Admin	assigned JO-8433	Marco Lee · VAN-1280	just now	2026-09-17T11:41:10.452Z
2e861537-81ba-4118-8338-abe48eaf3918	RZ	Admin	dispatched BK-4F8D0689	A to B · JO-8432	just now	2026-09-17T11:41:10.481Z
362c3d04-d99c-4d24-9ce3-2ed0abf02637	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-17T11:41:10.506Z
fcbbed1a-ccd2-43ae-8145-5c94de0e866f	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-17T11:41:10.516Z
13d12b20-8e98-4b22-9448-89873bc3a7bd	OP	Sarah Kim	moved JO-8432 to en_route	Op Test to Op Dest	just now	2026-09-17T11:41:10.527Z
30ec2e95-cbdd-45e0-bd69-7fc6171dfa42	OP	Sarah Kim	moved JO-8432 to arrived	Op Test to Op Dest	just now	2026-09-17T11:41:10.533Z
d91aa89c-5d07-493c-a3f7-17febafe8e9d	OP	Sarah Kim	moved JO-8432 to picked_up	Op Test to Op Dest	just now	2026-09-17T11:41:10.540Z
784e8790-e115-4e45-8b99-7311020bf212	OP	Sarah Kim	moved JO-8432 to delivered	Op Test to Op Dest	just now	2026-09-17T11:41:10.545Z
95431d52-61bb-4e01-99df-75d1c443f2f8	OP	Sarah Kim	uploaded proof for JO-8432	test.png	just now	2026-09-17T11:41:10.554Z
25fc3878-43a3-4b3a-ba8f-e2884941dd96	RZ	Admin	removed vehicle VH-001	Fleet roster updated	just now	2026-09-18T10:35:58.392Z
cf58948d-bf24-4ef9-9366-48f0667d8ed1	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-18T10:55:37.523Z
13f8c15d-8ca3-4391-b604-170577976e66	RZ	Admin	updated JO-8432	Updated From to FT To	just now	2026-09-18T10:58:19.022Z
94f4387e-7c73-4817-834f-fef9cbc89a88	RZ	Admin	removed JO-8432	Updated From to FT To	just now	2026-09-18T10:58:19.055Z
0d64662c-8f2a-4540-b984-d5c5d4d53e37	RZ	Admin	dispatched BK-0F3D1060	FT Pickup to FT Dropoff · JO-8432	just now	2026-09-18T10:58:19.219Z
64ab02c4-fae7-456f-b468-f34992389fce	RZ	Admin	added vehicle FT-1234	Ford Test Van	just now	2026-09-18T10:58:19.290Z
e60d0de0-0bc1-4a0d-8ec5-32db301dc805	RZ	Admin	updated FT-5678	Ford Updated Model	just now	2026-09-18T10:58:19.315Z
0189d0ff-b582-4a3c-ba3e-11ce5a3849c7	RZ	Admin	removed vehicle VH-010	Fleet roster updated	just now	2026-09-18T10:58:19.330Z
92e1c731-eb50-4ea0-a502-f2271b72c279	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-18T10:58:19.362Z
df70278e-507b-4b6f-afcc-de78b027d226	RZ	Admin	assigned JO-8433	Marco Lee · VAN-0842	just now	2026-09-18T10:58:19.434Z
40d8d92b-7805-49b8-b5de-ae5e17991217	RZ	Admin	dispatched BK-AB92672F	A to B · JO-8432	just now	2026-09-18T10:58:19.506Z
771b4174-cad6-48ed-8e7e-b68455a4a2bf	RZ	Admin	optimized dispatch route	5 active loads sequenced	just now	2026-09-18T10:58:19.566Z
c939b007-ab40-4f25-ad2f-285d3aecb60e	RZ	Admin	assigned JO-8432	Sarah Kim · SED-9201	just now	2026-09-18T10:58:19.586Z
300cc624-22ea-4275-820c-2368604e9be8	OP	Sarah Kim	moved JO-8432 to en_route	Op Test to Op Dest	just now	2026-09-18T10:58:19.608Z
00afc298-2958-44b0-97bf-ea9d12641e03	OP	Sarah Kim	moved JO-8432 to arrived	Op Test to Op Dest	just now	2026-09-18T10:58:19.620Z
54c7398e-c068-4f3c-9369-e2e90047c260	OP	Sarah Kim	moved JO-8432 to picked_up	Op Test to Op Dest	just now	2026-09-18T10:58:19.631Z
fcc35de6-979b-4ba0-8872-223f959d6d77	OP	Sarah Kim	moved JO-8432 to delivered	Op Test to Op Dest	just now	2026-09-18T10:58:19.643Z
0175e900-6e6a-47e6-8b34-d1d6ec13a335	OP	Sarah Kim	uploaded proof for JO-8432	test.png	just now	2026-09-18T10:58:19.662Z
\.
COPY public.bookings (id, quote_id, customer_name, email, phone, service_type, pickup_address, dropoff_address, service_date, vehicle_type, miles, passengers, hours, notes, quote_total, status, created_at) FROM stdin;
BK-687C5B9E	Q-364177BB	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T08:18:37.997Z
BK-81DBAE41	Q-AAED9A2E	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T08:21:21.148Z
BK-351D8C10	Q-F7C4D5C7	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T08:21:41.822Z
BK-8B5803E5	Q-B8AB5959	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T08:24:14.813Z
BK-5E60C557	Q-4A1EE7AE	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T08:25:30.655Z
BK-AB8142B5	Q-0310CB81	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T08:29:32.670Z
BK-D12F26B4	Q-75E4B585	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:03:47.934Z
BK-1C9BE8E9	Q-EB00F1ED	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:07:25.410Z
BK-C437CA41	Q-43BF0905	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:08:25.590Z
BK-D700FAE6	Q-1AB98F0D	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:11:10.928Z
BK-CBB9A8DB	Q-58DD5765	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:14:19.551Z
BK-2B24E089	Q-7D975C7F	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:17:32.967Z
BK-D98E3D06	Q-359FED6C	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:18:43.409Z
BK-4A185116	Q-3839DCB6	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:21:37.845Z
BK-A6F717EF	Q-284C9D31	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:27:00.093Z
BK-B39F2F0F	Q-24383EF2	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:34:56.536Z
BK-C124D47A	Q-64B88AE9	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:44:37.648Z
BK-28256A0A	Q-A457AD43	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T09:54:36.973Z
BK-DFBC61CB	Q-99759FC5	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T10:00:23.775Z
BK-AD6B8674	Q-B25980A8	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T10:04:45.820Z
BK-BE620B8B	Q-39352F57	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T10:19:49.025Z
BK-34B5EEE7	Q-99893B6F	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T10:21:11.952Z
BK-0D829456	Q-84BED893	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-13T10:38:43.424Z
BK-F116DA1A	Q-A9EA941A	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T11:59:44.628Z
BK-C6A5AE11	Q-7D88CD49	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T13:25:39.505Z
BK-AB1C2FBD	Q-C9B34F18	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T13:28:08.762Z
BK-157861FD	Q-11E26FA6	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T13:29:27.782Z
BK-9AF476B2	Q-6AEB9AC1	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T13:43:10.001Z
BK-CF48ABD3	Q-3878B092	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T13:51:26.820Z
BK-31FD4739	Q-2E41F405	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T14:37:24.077Z
BK-5455DC6D	Q-9DF92BE2	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T14:42:21.854Z
BK-137B98EA	Q-06B89005	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T14:50:29.907Z
BK-31F94A68	Q-9806AE43	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T14:58:41.344Z
BK-72350674	Q-D48FAF67	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:22:16.035Z
BK-0DD230FA	Q-6ED9B615	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:22:47.532Z
BK-0A6F8010	Q-2F3DF72C	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:23:26.484Z
BK-81FA5FDC	Q-D4E85AFB	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:37:58.259Z
BK-E802816E	Q-AA417E97	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:39:10.167Z
BK-0017ECE2	Q-D2A34DD9	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:39:33.392Z
BK-CD4FEC66	Q-DC9DCA16	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:40:38.934Z
BK-79E56575	Q-A077FB09	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:41:20.100Z
BK-BDB11FBD	Q-478A64F8	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:41:35.221Z
BK-92B27CF7	Q-065CACB3	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:44:50.738Z
BK-9C874AFE	Q-2285E01C	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T15:53:16.440Z
BK-1473ACC7	Q-BABE00F8	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T16:04:02.994Z
BK-FDBE58D2	Q-5C9AF97E	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T16:07:47.600Z
BK-5A475F7A	Q-7005201C	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T16:11:52.905Z
BK-26B955CC	Q-047E2C79	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T16:31:00.361Z
BK-519ADBD4	Q-789D6FBA	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T16:39:18.779Z
BK-64163760	Q-AE6B8745	maria lopez	maria@companygmail.com	(415)555-0914	charter	123 Mission Street	SFO TERMINAL3	2026-09-15	van	45	3	3		1190.61	booked	2026-09-14T17:03:08.751Z
BK-958BC02C	Q-F7993A1C	MARIA LOPEZ	zaniqrao22@gmail.com	0332 6345628	same-day	123 MISSION STREET	SFO TERMINAL 3	2026-09-15	car	18	2	3		176.9	booked	2026-09-14T17:06:10.275Z
BK-B8A0E27C	Q-8848B85D	zaniq rao	zaniq22@gmail.com	0332 6345628	same-day	123 mission street	sfo terminal3	2026-09-15	car	18	2	3		176.9	booked	2026-09-14T17:12:52.751Z
BK-B6C1C218	Q-3FF416A7	zaniq	zaniq22@gmail.com	03326345628	same-day	123 main street	sfo terminal 3	2026-09-15	car	23	10	8		990.66	booked	2026-09-14T17:21:27.547Z
BK-C9BA708C	Q-2C057FE2	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T17:39:07.661Z
BK-D1C74C70	Q-2F0640BA	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T17:52:33.764Z
BK-80A79432	Q-86C98181	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-14T18:08:55.816Z
BK-5A78ED08	Q-5781B45F	zaniq	zaniq@gmail.com	122435436457	same-day	123 main street	sfo terminal3	2026-09-15	car	18	2	3		176.9	booked	2026-09-14T18:11:24.152Z
BK-0F4BDBFB	Q-780FC995	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	booked	2026-09-15T11:32:29.681Z
\.
COPY public.drivers (id, name, initials, phone, email, vehicle, status, rating, jobs_completed, created_at) FROM stdin;
DR-103	Daniel Ruiz	DR			Truck 21	On route	4.9	11	2026-09-15T17:21:32.115Z
DR-104	Avery Chen	AC			Van 04	On route	4.7	5	2026-09-15T17:21:32.115Z
DR-102	Sarah Kim	SK			Van 08	On route	4.8	6	2026-09-15T17:21:32.114Z
DR-101	Marco Lee	ML			Van 12	Available	4.9	8	2026-09-15T17:21:32.113Z
\.
COPY public.jobs (id, type, priority, from_address, to_address, time, distance, price, status, driver, route_order, created_at, booking_id, vehicle_id) FROM stdin;
JO-8427	PICKUP	Standard	SFO Terminal 3	Downtown Hotel	Sun, Sep 20 · airport transfer	18 mi	$0.00	completed	Sarah Kim	\N	2026-09-14T17:16:05.531Z	BK-519ADBD4	\N
JO-8421	PICKUP	High priority	1280 Market Street	77 Geary Street	Today, 10:40 AM	2.4 mi	$42.80	completed	Sarah Kim	\N	2026-09-13T07:32:36.634Z	\N	\N
JO-8428	PICKUP	Standard	SFO Terminal 3	Downtown Hotel	Sun, Sep 20 · airport transfer	18 mi	$0.00	completed	Sarah Kim	\N	2026-09-14T17:16:07.748Z	BK-26B955CC	\N
JO-8426	PICKUP	Standard	123 Mission Street	SFO TERMINAL3	Tue, Sep 15 · charter	45 mi	$1190.61	completed	Sarah Kim	\N	2026-09-14T17:16:02.738Z	BK-64163760	\N
JO-8429	PICKUP	Standard	123 main street	sfo terminal3	Today, 11:20 AM	Pending	Pending	completed	Sarah Kim	\N	2026-09-14T17:18:22.695Z	\N	\N
JO-8415	PICKUP	High priority	85 2nd Street	Mission Bay	Today, 10:54 AM	4.8 mi	$51.60	completed	Sarah Kim	\N	2026-09-13T07:32:36.634Z	\N	\N
JO-8418	DELIVERY	Standard	420 Hayes Street	16th & Valencia	Today, 10:48 AM	3.1 mi	$38.20	completed	Sarah Kim	\N	2026-09-13T07:32:36.634Z	\N	\N
JO-8409	DELIVERY	Standard	601 4th Street	Pier 39	Today, 11:02 AM	5.2 mi	$44.10	completed	Sarah Kim	\N	2026-09-13T07:32:36.634Z	\N	\N
JO-8424	PICKUP	Standard	123 mission street	sfo terminal3	Tue, Sep 15 · same day	18 mi	$176.90	queued	\N	1	2026-09-14T17:15:54.174Z	BK-B8A0E27C	\N
JO-8425	PICKUP	Standard	123 MISSION STREET	SFO TERMINAL 3	Tue, Sep 15 · same day	18 mi	$176.90	queued	\N	2	2026-09-14T17:15:58.541Z	BK-958BC02C	\N
JO-8430	DELIVERY	Standard	SFO Terminal 3	Downtown Hotel	Sun, Sep 20 · airport transfer	18 mi	$0.00	queued	\N	3	2026-09-14T17:52:40.756Z	BK-D1C74C70	\N
JO-8431	PICKUP	Standard	SFO Terminal 3	Downtown Hotel	Sun, Sep 20 · airport transfer	18 mi	$0.00	queued	\N	4	2026-09-14T18:08:06.146Z	BK-C9BA708C	\N
JO-8422	PICKUP	Standard	1 Main St	2 Mission St	Today, 11:20 AM	Pending	Pending	queued	\N	5	2026-09-14T14:55:54.177Z	\N	\N
\.
COPY public.licenses (id, user_id, license_key, type, status, stripe_session_id, customer_email, source, created_at) FROM stdin;
LIC-2a67e9c1-c738-497d-a1ed-4de4851142ec	b032b84a-af8e-49e8-a975-4134e5ca1cd3	RZ-0FDEC05DCACFEEEB528879E369DE6790	lifetime	active	\N	demokey@example.com	demo	2026-09-14T15:44:45.063Z
LIC-cccade5d-3c2d-41be-913d-84c0978b8e09	09234eeb-c573-47ea-9651-7268d99ba807	RZ-D57979F6417A18E1AD8167DF2179970D	lifetime	active	\N	typedkey@example.com	demo	2026-09-14T15:44:45.286Z
LIC-4e87f917-4ac5-4a6a-bc5e-a8f822ae1b32	\N	RZ-ED4179B9DBC69C41EF95A61118256F57	lifetime	active	demo_123	buyer@example.com	manual	2026-09-15T11:32:29.566Z
LIC-d86d6b75-d2a7-4580-8d80-612088bdbdfd	saas-user-1	RZ-89A94B5A3FECEA4556654461DB87E067	lifetime	active	\N	owner@example.com	test	2026-09-15T11:32:29.654Z
LIC-3ffcd640-13c8-4296-a029-55a5c56ba6f4	d5e33544-b447-48ec-ba18-ee40a6c8fc8d	RZ-4010A1E1C2C4AD2AE047BAB70DE83AC2	lifetime	active	\N	demo_user_7693@test.com	demo	2026-09-14T15:17:47.569Z
LIC-a7293327-6404-4f4a-a92e-ef24dd4401ac	c6984d25-02a0-41cf-b126-7360bb1d7a99	RZ-0CC8B04D0576A11AF11993883BBD7C25	lifetime	active	\N	multi_a_81802@test.com	demo	2026-09-14T15:22:09.087Z
LIC-0e081a10-e4c3-44f9-8188-fa1ed018ff3a	67432844-1d89-4ebc-970b-cadc59bed3fc	RZ-6D5133D3DB8BF6DD7A0533E8C7516B67	lifetime	active	\N	multi_b_935@test.com	demo	2026-09-14T15:22:09.948Z
LIC-7ed87e17-a354-46bb-b998-11a569259d93	ee97eb61-26c4-4251-bd3a-68298d05f0df	RZ-632C1DFD832557F877143B1ADDD431BB	lifetime	active	\N	cust_1789399336472@test.com	demo	2026-09-14T15:22:17.406Z
\.
COPY public.messages (id, sender, initials, subject, body, type, is_read, created_at) FROM stdin;
b463f8d6-69af-43b0-85cf-d3479f87406d	Sarah Kim	SK	Pickup delayed at 420 Hayes	Traffic is building near the pickup. I can still make the revised ETA if the next load is pushed by ten minutes.	operations	1	2026-09-13T09:17:32.949Z
baa3d265-8eda-44c0-ad7a-5dc4abdf8a94	System	RZ	Route optimization applied	Your active loads were sequenced using priority and known distance.	system	1	2026-09-13T08:57:32.949Z
60a8743f-e902-4ad8-ad09-a3193f62a943	Marco Lee	ML	Vehicle inspection complete	Van 12 passed inspection and is ready for another route.	fleet	1	2026-09-13T09:07:32.949Z
fe2634e1-1657-4a19-b72b-6c63f9f2fc35	admin@rzdispatch.local	AD	Feature Test	Automated test message	operations	1	2026-09-15T18:12:43.251Z
57a88966-ffed-4742-abd4-a35a2ade65ac	admin@rzdispatch.local	AD	Feature Test	Automated test message	operations	1	2026-09-17T11:35:46.366Z
3f483169-4781-4e80-aac2-47976f104fa2	admin@rzdispatch.local	AD	Feature Test	Automated test message	operations	1	2026-09-17T11:41:10.143Z
f41b231f-5295-4da4-8e87-7d88d2980514	admin@rzdispatch.local	AD	Feature Test	Automated test message	operations	1	2026-09-18T10:58:18.844Z
\.
COPY public.proof_documents (id, job_id, operator_id, file_name, mime_type, file_path, byte_size, created_at) FROM stdin;
899bace1-3bb4-4193-9f09-afbcb0b1b779	JO-8432	f3c95374-9d79-4794-9930-3e57b8c76e74	test.png	image/png	proof\\899bace1-3bb4-4193-9f09-afbcb0b1b779.png	70	2026-09-18T10:58:19.658Z
\.
COPY public.quotes (id, customer_name, email, phone, service_type, pickup_address, dropoff_address, service_date, vehicle_type, miles, passengers, hours, notes, quote_total, status, created_at) FROM stdin;
Q-364177BB	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T08:18:37.997Z
Q-AAED9A2E	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T08:21:21.148Z
Q-7F06F8F7	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T08:21:21.149Z
Q-F7C4D5C7	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T08:21:41.822Z
Q-67007306	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T08:21:41.822Z
Q-B8AB5959	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T08:24:14.813Z
Q-6AB4B9E6	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T08:24:14.815Z
Q-4A1EE7AE	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T08:25:30.654Z
Q-05F367FA	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T08:25:30.655Z
Q-0310CB81	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T08:29:32.670Z
Q-3E6F1C17	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T08:29:32.670Z
Q-75E4B585	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:03:47.934Z
Q-4AABB96B	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:03:47.934Z
Q-EB00F1ED	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:07:25.410Z
Q-2FDE2777	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:07:25.410Z
Q-43BF0905	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:08:25.590Z
Q-6142CF2B	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:08:25.591Z
Q-1AB98F0D	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:11:10.928Z
Q-3B92F43F	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:11:10.929Z
Q-58DD5765	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:14:19.550Z
Q-EC7AFCE2	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:14:19.551Z
Q-7D975C7F	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:17:32.966Z
Q-A11ACA5F	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:17:32.967Z
Q-359FED6C	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:18:43.409Z
Q-5D932C06	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:18:43.409Z
Q-3839DCB6	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:21:37.845Z
Q-08627448	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:21:37.846Z
Q-284C9D31	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:27:00.093Z
Q-90C148E1	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:27:00.094Z
Q-24383EF2	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:34:56.535Z
Q-5B02D4D9	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:34:56.536Z
Q-64B88AE9	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:44:37.647Z
Q-CD260618	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:44:37.648Z
Q-A457AD43	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T09:54:36.972Z
Q-DB81540F	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T09:54:36.973Z
Q-99759FC5	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T10:00:23.774Z
Q-8C6B6CBC	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T10:00:23.775Z
Q-B25980A8	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T10:04:45.820Z
Q-C0E866B0	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T10:04:45.821Z
Q-39352F57	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T10:19:49.025Z
Q-4A5D93B4	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T10:19:49.026Z
Q-99893B6F	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T10:21:11.952Z
Q-53328204	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T10:21:11.953Z
Q-84BED893	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-13T10:38:43.423Z
Q-27E96AA6	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-13T10:38:43.424Z
Q-A9EA941A	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T11:59:44.626Z
Q-AFA5BBF3	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T11:59:44.629Z
Q-7D88CD49	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T13:25:39.497Z
Q-98F14980	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T13:25:39.507Z
Q-C9B34F18	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T13:28:08.760Z
Q-15B15348	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T13:28:08.763Z
Q-11E26FA6	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T13:29:27.780Z
Q-4F91D40B	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T13:29:27.783Z
Q-6AEB9AC1	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T13:43:10.000Z
Q-A805DFCA	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T13:43:10.002Z
Q-3878B092	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T13:51:26.818Z
Q-176FF16D	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T13:51:26.822Z
Q-2E41F405	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T14:37:24.075Z
Q-CB7C7551	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T14:37:24.079Z
Q-9DF92BE2	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T14:42:21.853Z
Q-FA71D98D	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T14:42:21.856Z
Q-06B89005	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T14:50:29.906Z
Q-EF78E8CB	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T14:50:29.908Z
Q-9806AE43	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T14:58:41.342Z
Q-2C4BA616	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T14:58:41.345Z
Q-D48FAF67	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:22:16.034Z
Q-CC89AC6B	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:22:16.037Z
Q-6ED9B615	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:22:47.531Z
Q-988E1EA3	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:22:47.534Z
Q-2F3DF72C	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:23:26.483Z
Q-3706A26B	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:23:26.485Z
Q-D4E85AFB	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:37:58.258Z
Q-1501E8D4	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:37:58.260Z
Q-AA417E97	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:39:10.166Z
Q-34801036	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:39:10.168Z
Q-D2A34DD9	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:39:33.390Z
Q-12BCBE2C	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:39:33.393Z
Q-DC9DCA16	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:40:38.932Z
Q-31BBA122	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:40:38.935Z
Q-A077FB09	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:41:20.099Z
Q-4C5E3D11	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:41:20.100Z
Q-478A64F8	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:41:35.220Z
Q-1CF0C84E	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:41:35.221Z
Q-065CACB3	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:44:50.737Z
Q-D2127071	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:44:50.739Z
Q-2285E01C	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T15:53:16.439Z
Q-A90681B9	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T15:53:16.441Z
Q-BABE00F8	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T16:04:02.993Z
Q-A22A214E	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T16:04:02.995Z
Q-5C9AF97E	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T16:07:47.599Z
Q-0D23C9AF	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T16:07:47.600Z
Q-7005201C	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T16:11:52.904Z
Q-FD5CE58E	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T16:11:52.906Z
Q-047E2C79	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T16:31:00.360Z
Q-CB8E6B7E	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T16:31:00.362Z
Q-789D6FBA	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T16:39:18.778Z
Q-0B64D8D4	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T16:39:18.780Z
Q-AE6B8745	maria lopez	maria@companygmail.com	(415)555-0914	charter	123 Mission Street	SFO TERMINAL3	2026-09-15	van	45	3	3		1190.61	accepted	2026-09-14T17:03:08.748Z
Q-F7993A1C	MARIA LOPEZ	zaniqrao22@gmail.com	0332 6345628	same-day	123 MISSION STREET	SFO TERMINAL 3	2026-09-15	car	18	2	3		176.9	accepted	2026-09-14T17:06:10.268Z
Q-8848B85D	zaniq rao	zaniq22@gmail.com	0332 6345628	same-day	123 mission street	sfo terminal3	2026-09-15	car	18	2	3		176.9	accepted	2026-09-14T17:12:52.747Z
Q-3FF416A7	zaniq	zaniq22@gmail.com	03326345628	same-day	123 main street	sfo terminal 3	2026-09-15	car	23	10	8		990.66	accepted	2026-09-14T17:21:27.542Z
Q-2C057FE2	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T17:39:07.660Z
Q-ECF78203	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T17:39:07.662Z
Q-2F0640BA	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T17:52:33.763Z
Q-32B31FCC	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T17:52:33.765Z
Q-86C98181	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-14T18:08:55.815Z
Q-8F7BEADE	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-14T18:08:55.817Z
Q-5781B45F	zaniq	zaniq@gmail.com	122435436457	same-day	123 main street	sfo terminal3	2026-09-15	car	18	2	3		176.9	accepted	2026-09-14T18:11:24.145Z
Q-780FC995	Alicia Reed	alicia@example.com	555-0102	airport-transfer	SFO Terminal 3	Downtown Hotel	2026-09-20	car	18	2	1	Need early pickup	0	pending	2026-09-15T11:32:29.680Z
Q-52E9C95F	Jordan Bell	jordan@example.com	555-0199	airport-transfer	Downtown Office	SFO Terminal 4	2026-09-25	suv	16	3	2	Late flight	144.92	pending	2026-09-15T11:32:29.682Z
\.
COPY public.service_zones (key, name, boundary, base_surcharge, distance_surcharge, active, updated_at) FROM stdin;
downtown-sf	Downtown San Francisco	37.7749,-122.4194;37.7955,-122.3937	0	0	1	2026-09-13T09:54:36.948Z
south-bay	San Mateo & South Bay	37.4419,-122.1430;37.6879,-122.4702	8	0.35	1	2026-09-13T09:54:36.948Z
east-bay	East Bay	37.8044,-122.2712;37.6879,-122.4702	12	0.5	1	2026-09-13T09:54:36.948Z
north-bay	North Bay	38.1041,-122.5697;37.8272,-122.4796	15	0.65	1	2026-09-13T09:54:36.948Z
airport-corridors	Airport corridors	37.6213,-122.3790;37.7126,-122.2120	10	0.25	1	2026-09-15T17:37:36.093Z
\.
COPY public.services (key, name, description, base_price, distance_rate, hourly_rate, active, updated_at) FROM stdin;
same-day	Same-day ride	Fast local transportation for urgent trips and business needs.	45	2.25	0	1	2026-09-13T09:44:37.625Z
hourly	Hourly charter	Flexible multi-stop transport with a dedicated chauffeur.	55	0	55	1	2026-09-13T09:44:37.625Z
airport-transfer	Airport transfer	Flight-aware pickups and drop-offs for SFO, OAK, and SJC.	68	2.75	0	1	2026-09-14T16:38:58.929Z
charter	Full charter	Private group transportation for teams and events.	119	3.5	110	1	2026-09-15T17:37:16.072Z
\.
COPY public.support_tickets (id, user_id, email, subject, message, status, created_at) FROM stdin;
TK-FC63AE14	880cacd7-227e-4a1b-a359-22a96f2dde37	admin@rzdispatch.local	Account Access	Cannot sign in on the second device.	open	2026-09-14T15:52:50.903Z
\.
COPY public.user_settings (user_id, name, phone, notify_email, notify_sms, notify_inapp, updated_at) FROM stdin;
f3c95374-9d79-4794-9930-3e57b8c76e74	Operator		1	0	1	2026-09-15T18:00:02.851Z
880cacd7-227e-4a1b-a359-22a96f2dde37	Admin		1	0	1	2026-09-17T17:06:17.095Z
\.
COPY public.users (id, email, password_hash, role, driver_id, created_at) FROM stdin;
76fd4575-575b-434a-a826-f201c5b65b7d	admin@rzdipatch.local	$2b$12$RO5JKX.2SydlF7Ofzm8y2OwEp.9NBZHS.pcE/BnQYkjMU49vKU3Qi	owner	\N	2026-09-13T07:55:48.340Z
f3c95374-9d79-4794-9930-3e57b8c76e74	operator@rzdispatch.local	$2b$12$tx0cLgpcIcYTfb9ytbrbBuwO/u16acXYu0700i/ZWPHfQskBFy3aW	operator	DR-102	2026-09-13T10:19:49.001Z
5074c7cf-5c83-4ec6-b525-0a51c2ef7290	broke_1789398489672@test.com	$2b$12$ujMzeszwvTgc0CiIwcirk.vpyWJqQNTCyXN/z8o2ZfwbsSfyZB5fO	owner	\N	2026-09-14T15:08:10.653Z
f1aa0f25-7e90-4afd-88de-cac89c34a8a0	cust_1789398548624@test.com	$2b$12$g4y7UKn8rykgsaqpT0Y0f.6j4/lHpbnICg08qosh76/JIm.A0a6sK	owner	\N	2026-09-14T15:09:09.538Z
6b4222a5-5f9a-461a-9151-020414e99d0b	cust_1789398904907@test.com	$2b$12$TStsOxRQphq3ulpRlB1lZehfCL5T/RJlJEXRABYHurYHBAtTrVPUq	owner	\N	2026-09-14T15:15:05.977Z
3a2a15aa-7bfd-4c30-b793-7b9c984e8b91	cust_1789398966760@test.com	$2b$12$qKogv9dyuB4qzk7asJreB.vzTQ6mmCU./ChJrm935U0Mx7I0uxDqK	owner	\N	2026-09-14T15:16:07.737Z
d5e33544-b447-48ec-ba18-ee40a6c8fc8d	demo_user_7693@test.com	$2b$12$jtISnVWGhNvf15dVN06XUe8kMopovdkkDyQKOA8sWc4iwYleUnDwS	owner	\N	2026-09-14T15:17:47.412Z
37f61c85-7c25-44c8-aa52-02c9262b8a12	final_57999@test.com	$2b$12$fYHq2aWbGZGIzmmK4VkdkeE8bY2HdiYREtrcEwk8WT/dWb06aPJ5a	owner	\N	2026-09-14T15:20:23.908Z
c6984d25-02a0-41cf-b126-7360bb1d7a99	multi_a_81802@test.com	$2b$12$5ww9QM5okZILsf6mKOPKvupBiN6DEt13JROozLi3hU4BZvtyjQRm6	owner	\N	2026-09-14T15:22:08.991Z
67432844-1d89-4ebc-970b-cadc59bed3fc	multi_b_935@test.com	$2b$12$yoFkQE8HwsoAkBvJLhbMc.ntBBg4k3Jaq7HTcQ.jw2V2D85RLW/4a	owner	\N	2026-09-14T15:22:09.935Z
ee97eb61-26c4-4251-bd3a-68298d05f0df	cust_1789399336472@test.com	$2b$12$xc1n97HMNH8RFu8pHmlvNe.omDNGGgtnIknvdMgisxCHBqM9gQy1C	owner	\N	2026-09-14T15:22:17.334Z
b032b84a-af8e-49e8-a975-4134e5ca1cd3	demokey@example.com	$2b$12$iafs/e5lx.ICcu1eRm4nHeRlxqIHSNEJ/cl1JTJYQ8NAukdsF29na	owner	\N	2026-09-14T15:44:45.055Z
09234eeb-c573-47ea-9651-7268d99ba807	typedkey@example.com	$2b$12$aZSt5hL64sz8.MGVbuCUwuKEIAk7OnBDbDoanQlT/JLYNRLeO3qAW	owner	\N	2026-09-14T15:44:45.281Z
880cacd7-227e-4a1b-a359-22a96f2dde37	admin@rzdispatch.local	$2b$12$FGwNNy9TxfblFeyKKtQJVerr6iqycGY8fmWhb0igj/UfIks9q/oWy	admin	\N	2026-09-13T07:32:36.633Z
\.
COPY public.vehicles (id, plate, make, model, year, vehicle_type, capacity, status, driver_id, mileage, created_at) FROM stdin;
VH-004	VAN-0477	Mercedes	Sprinter	2023	van	14	available	\N	51230	2026-09-14T16:03:47.181Z
VH-005	SED-9201	Toyota	Camry	2025	sedan	4	available	\N	8120	2026-09-14T16:03:47.181Z
VH-008	LUX-7700	Mercedes	S-Class	2025	luxury	3	available	\N	12680	2026-09-14T16:03:47.182Z
VH-002	VAN-0842	Ford	Transit	2023	van	12	available	\N	38720	2026-09-14T16:03:47.180Z
VH-003	TRK-2100	Ford	F-550	2024	truck	4	available	\N	29450	2026-09-14T16:03:47.181Z
VH-007	VAN-3391	Ram	ProMaster	2023	van	10	available	\N	44890	2026-09-14T16:03:47.182Z
VH-006	SUV-5530	Toyota	Highlander	2024	suv	7	available	\N	62340	2026-09-14T16:03:47.182Z
VH-009	VAN-98	mercedez	transit	2026	sedan	4	available	\N	0	2026-09-15T17:35:28.620Z
\.
