require('dotenv').config();
const fs = require('fs');
const path = require('path');

async function main() {
  const { ensureDatabase } = require('./ensure-database');
  const { initializeDatabase } = require('../server');
  await ensureDatabase();
  await initializeDatabase();

  const db = require('../db');

  const tablesResult = await db.all(`SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename <> 'schema_migrations' ORDER BY tablename`);
  const tables = tablesResult.map((row) => row.tablename);

  const backupDir = path.join(__dirname, '..', 'backups');
  if (!fs.existsSync(backupDir)) fs.mkdirSync(backupDir, { recursive: true });

  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const filePath = path.join(backupDir, `rz_backup_${stamp}.sql`);
  const stream = fs.createWriteStream(filePath);

  stream.write(`-- RZ Dispatch backup created ${new Date().toISOString()}\n`);
  stream.write(`-- Generated by scripts/backup.js\n\n`);

  for (const table of tables) {
    const colRows = await db.all(`SELECT column_name, data_type, is_nullable, column_default FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '${table}' ORDER BY ordinal_position`);
    const pkRows = await db.all(`SELECT kcu.column_name FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema WHERE tc.table_schema = 'public' AND tc.table_name = '${table}' AND tc.constraint_type = 'PRIMARY KEY' ORDER BY kcu.ordinal_position`);
    const pkSet = new Set(pkRows.map((row) => row.column_name));

    const columnDefs = colRows.map((row) => {
      const base = row.data_type === 'character varying' ? 'TEXT' : row.data_type === 'integer' ? 'INTEGER' : row.data_type === 'smallint' ? 'SMALLINT' : row.data_type === 'timestamp with time zone' || row.data_type === 'timestamp without time zone' ? 'TEXT' : row.data_type.toUpperCase();
      const parts = [row.column_name, base];
      if (row.is_nullable === 'NO' && !pkSet.has(row.column_name)) parts.push('NOT NULL');
      if (row.column_default !== null && !row.column_default.startsWith('nextval(')) parts.push(`DEFAULT ${row.column_default}`);
      return parts.join(' ');
    });
    const pkCols = [...pkSet];
    let ddl = `CREATE TABLE public.${table} (\n  ${columnDefs.join(',\n  ')}`;
    if (pkCols.length) ddl += `,\n  PRIMARY KEY (${pkCols.join(', ')})`;
    ddl += '\n);\n';
    stream.write(`${ddl}\n`);

    const rows = await db.all(`SELECT * FROM ${table}`);
    if (!rows.length) continue;
    const columns = Object.keys(rows[0]);
    stream.write(`COPY public.${table} (${columns.join(', ')}) FROM stdin;\n`);
    for (const row of rows) {
      const values = columns.map((column) => {
        const value = row[column];
        if (value === null || value === undefined) return '\\N';
        return String(value).replace(/\\/g, '\\\\').replace(/\t/g, '\\t').replace(/\n/g, '\\n').replace(/\r/g, '\\r');
      });
      stream.write(values.join('\t') + '\n');
    }
    stream.write('\\.\n');
    console.log(`[backup] dumped ${table} (${rows.length} rows)`);
  }

  stream.end();
  await new Promise((resolve) => stream.on('finish', resolve));
  await db.close();
  console.log(`[backup] wrote ${filePath}`);
}

main().catch((error) => {
  console.error('[backup] failed:', error);
  process.exit(1);
});